language: node_js
before_install: npm prune
before_cache: npm prune
install: npm install
script:
- npm run test-ci
- npm run doc
- npm run test:perf
branches:
  only:
  - master
  - develop
sudo: false
cache:
  directories:
  - node_modules
env:
  global:
  - SAUCE_USERNAME=as-helper-js
  - secure: zHtXU8LLLHwoXiOeHsUSXJVLMVUEelCfsZI5bUTyp/vy4ZZ5zPr8r9oPKZAHhQXii6PYFwW4rgP0/5BJ8Ono/axDIDPHg9YNoAbajnco31mYJEsxN+4hi/6rkmJWxqXprRvqEfiEIPY0FSaJEv9rOpJRZX2rycP3MH2vHwZKNXo=
  - secure: kxNWq4D6Tv7c/h2kutn3tPVU6m02IYlHFQgNLlzxHmnAh0OFbHFeXFu1d6ng0m0BQqK4JIuCLJudN3U9HAGFeYwxizM3ozkbMsOfuhZ2aoisLC40ber1x7eAh3vuVvHV3cDRwYvhvspLV6h8I9ggHiEye5Q2FEqBjg8Zm822/EM=
  - secure: Jj2WzeDLvGJlDT+OxIvgWqTOwORiziXs2uv/pjKwjKHgF8DA9pUBaz6q+s+2L2IAlcjkU3OliyVUQp8ajbhQKXwMM1a+bCQiiYgGWJ7hnn9bdzc4MPC1MljjAJ5yRn5iwX2GjqRS9v6VM3YTVp6QLSNR556g4Frg37TbGbzU01A=
  - secure: SkUTmFsPiw/SSCu9vIzx9oAV6TuTvfWt994hr0mTAqrsvRgMZj8YZTi/ck0gLfCkOE2FPxf2pJ0iHfgMm3s9dVSfckS1r4eNdLhOTfnaMf3lunVynqazjC5KJfpYDEzRf9CN0xqBTyyyA8X5lf91zrfCcptMtHxLBON2ACX/7BQ=
  - secure: iPXOsvcooWwQDKt9WdVe23dSvYncjINbgx8bBaZN9W40U/R3dBtdX/5WODAJ012Ku/EYPgWtixvQb7iJiQrrmf9O7FgY2YPUhJfjzxwHVcrX27bqoyrtAT9+wUT7TxDNOqdHBwd+SWPTnVQzrJT3cFsw4sj2v9F6TMEQbjxRFxA=
